#cloud-config
autoinstall:
  version: 1
  identity:
    hostname: ubuntu-dev
    username: developer
    password: "$6$ECNW7xPhOw2zY4fa$FGgpSNj5ukIknpULVlk5rD2l/wgcPmoQuqLsfCpwSi0TkWLJlCOc.6hvFE/q6dCvZjrYLmh66ayq6IVemZRCo."
    realname: Developer
  locale: en_US.UTF-8
  keyboard:
    layout: us
  storage:
    layout:
      name: direct
  apt:
    preserve_sources_list: false
    primary:
      - arches: [amd64, i386]
        uri: "http://archive.ubuntu.com/ubuntu"
      - arches: [default]
        uri: "http://ports.ubuntu.com/ubuntu-ports"
  packages:
    - python3
    - python3-pip
    - python3-venv
    - python3-dev
    - python3-flask
    - python3-django
    - python3-pandas
    - python3-numpy
    - python3-matplotlib
    - git
    - build-essential
    - curl
    - wget
    - vim
    - nano
  snaps:
    - name: code
      classic: true
  ssh:
    install-server: true
    allow-pw: true
  late-commands:
    - curtin in-target -- chage --lastday 0 developer
    - curtin in-target -- pip3 install flask django pandas numpy matplotlib jupyter
    - curtin in-target -- curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    - curtin in-target -- apt-get install -y nodejs
    - curtin in-target -- npm install -g npm nodemon express-generator webpack
    - curtin in-target -- bash -c "echo 'Welcome to your Ubuntu 24.04 development environment! For security reasons, you will be prompted to change your password at first login.' > /home/developer/README.txt"
    - curtin in-target -- chown developer:developer /home/developer/README.txt
